version: "3.4"
services:
  
  ui-api:
    build:
      context: ./UI/api
    ports:
      - 3894:3894
    volumes:
      - D:\Practice\Blockchain\MarketPlaceNFT\NFT-Markete\UI\api\storage:/NFT/UI/api/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    depends_on:
      - db
    ipc: host
    pid: host
    privileged: true


  # ui-beta:
  #   build:
  #     context: ./UI/client-beta
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db
      
  db:
    build:
      context: ./db
    ports:
      - "3306:3306"