version: "3.4"
services:
  
  ui-api:
    build:
      context: ./UI/api
    ports:
      - 3894:3894
    volumes:
      - /home/hp/Dev/react_practice/image-shell/UI/api/storage:/UI/api/storage
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/local/bin/docker:/usr/bin/docker
      #- /home/hp/Dev/react_practice/image-shell/First.sh:/First.sh
    depends_on:
      - db
    network_mode: host
    ipc: host
    pid: host
    privileged: true


  # ui-beta:
  #   build:
  #     context: ./UI/client-beta
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db
      
  db:
    build:
      context: ./db
    ports:
      - "3306:3306"