export const homeObjOne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../assets/images/svg1.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  dark2: false,
  darkText: false,
};
export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Unlimited access',
  headline: 'Login to your account at any time',
  description:
    'We have you covered no matter where you are located. All you need is an internet conection and a phone or computer.',
  buttonLabel: 'Learn more',
  imgStart: true,
  img: require('../../assets/images/svg2.svg'),
  alt: 'Piggy Bank',
  dark: true,
  primary: true,
  dark2: false,
  darkText: false,
};
export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Join our team',
  headline: 'Creating an account is extremely easy',
  description:
    'Get everything set and ready in under 10 minutes. All you need to do is add your information and you are ready to go.',
  buttonLabel: 'Start now',
  imgStart: false,
  img: require('../../assets/images/svg3.svg'),
  alt: 'Paper',
  dark: false,
  primary: false,
  dark2: false,
  darkText: false,
};
